#!/usr/bin/env bash
#
# skill-version.sh — Print the `version:` field from a skill's front matter.
#
# Several skills stamp a "Generated by /<skill> v<VERSION>" footer into the
# files they produce. Reading the field in-model would force the front matter
# to stay in context and let a wrong stamp pass unnoticed, because nothing
# checks a stamp after it is written. Reading it here removes both problems.
#
# Resolution order for the skills root:
#   1. The directory two levels above this script. Under the symlink install
#      that is ~/.claude/skills; under a plugin install it is wherever the
#      plugin unpacked to. Resolving from our own location covers both.
#   2. $HOME/.claude/skills, as a fallback for an unusual layout.
#
# Usage: skill-version.sh <skill-name>
#
# Output (one line on stdout):
#   The version string, e.g. 2026.09.16@ae50bfe
#
# Exit codes:
#   0  — success
#   1  — error (see stderr)

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: skill-version.sh <skill-name>

Prints the version: field from that skill's SKILL.md front matter.

  --help  Show this help message
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  usage
  exit 0
fi

readonly ERR_ARGS="V001"
readonly ERR_UNSAFE="V002"
readonly ERR_NOT_FOUND="V003"
readonly ERR_NO_VERSION="V004"

if [ "$#" -ne 1 ]; then
  echo "skill-version $ERR_ARGS error: expected exactly one skill name, got $#" >&2
  usage >&2
  exit 1
fi

name="$1"

# The name becomes one path segment, so refuse anything that could leave the
# skills directory. Same rule the identifier resolvers apply.
case "$name" in
  '' | '.' | '..' | */* | *' '*)
    echo "skill-version $ERR_UNSAFE error: '$name' is not usable as one path segment" >&2
    exit 1
    ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
candidates=(
  "$script_dir/../$name/SKILL.md"
  "$HOME/.claude/skills/$name/SKILL.md"
)

skill_file=""
for c in "${candidates[@]}"; do
  if [ -f "$c" ]; then
    skill_file="$c"
    break
  fi
done

if [ -z "$skill_file" ]; then
  echo "skill-version $ERR_NOT_FOUND error: no SKILL.md for '$name' under $script_dir/.. or $HOME/.claude/skills" >&2
  exit 1
fi

# Front matter only: the first block delimited by --- at column zero. A
# `version:` line further down the body is documentation, not the stamp.
version="$(awk '
  NR == 1 && $0 == "---" { infm = 1; next }
  infm && $0 == "---"    { exit }
  infm && /^version:[[:space:]]*/ {
    sub(/^version:[[:space:]]*/, "")
    print
    exit
  }
' "$skill_file")"

if [ -z "$version" ]; then
  echo "skill-version $ERR_NO_VERSION error: '$name' has no version: field in its front matter" >&2
  exit 1
fi

printf '%s\n' "$version"
