name: Markdownlint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19
        with:
          globs: "**/*.md"
