name: Markdownlint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"
